### PR TITLE
Add dashboard based on metadata

### PR DESCRIPTION
**Pull request by smacker**
Only charts based on fast data.
PR changes other dashboards too to make the ids correct.

Fix: #111

Screenshot_2019-06-18 Collaboration(2)

any improvements to the charts and layouts will be done by product team.

### CODE REVIEW

**Comment by smacker** [comment]
@se7entyse7en it's not smoothed on demo instance. I just re-implemented them here using demo as the source of truth:

Screenshot 2019-06-19 at 12 26 21


taking into account that Konst was working on it for quite a while, I assume it should be like that.

**Comment by se7entyse7en** [comment]
@smacker ok then, thanks for double checking it! 👍

**Comment by smacker** [comment]
we can always improve it later. (actually product team can improve it later :) )

**Comment by zurk** [comment]
FYI: `linear style` chart option does not work and changes nothing for this kind of plots. Where I did smoothing I did it directly in SQL query if it is not possible to smooth it in superset UI or here: 
Screen Shot 2019-06-19 at 17 30 06

Both options are not the best. But we have what we have :/

**Pull request merged**
