### PR TITLE
Update dashboards

### LINKED ISSUE #162: Charts disalignment in Collaboration dashboard
The charts “Average time to merge” and “Breakdown by pull request outcome" are not well aligned, the latter is taller.

Screenshot 2019-06-24 at 17 11 47

See #161.

### LINKED ISSUE #174: Welcome Dashboard Title styling on markdown files
I've just noticed that the Title on the Welcome Dashboard is not using Source Sans Pro, according to the new [Typography PR](https://github.com/src-d/sourced-ui/pull/139).

On the welcome dashboard markdown files we have:

```
.dashboard-markdown .dashboard-component.dashboard-component-chart-holder h1 {
    margin-top: 24px;
    margin-bottom: 24px;
    line-height: 1.6;
    font-size: 30px;
    font-weight: bold;
}
```

And we just need to add:

```
font-family: Source Sans Pro, Helvetica Neue, Arial, sans-serif;
```

Before:
image

After:
image

### LINKED ISSUE #211: Relative URLs in welcome dashboard markdown
Just noticed when running source{d} CE on a GCP cluster that the URLs in the welcome dashboards are not relative, but hard-coded with local server IP. E.g.:

```md
### Before you get started

You can come back to this Welcome dashboard at any point for references and information:
via browser navigation, [URL](http://127.0.0.1:8088/superset/dashboard/welcome-local/) or in the [list of dashboards](http://127.0.0.1:8088/dashboard/list/).

You can refer to the [source{d} CE full documentation](https://docs.sourced.tech/community-edition/) for more in-depth content.
```
```md
### Visualize your data on dashboards

- **[Explore source code-related use cases & metrics](http://127.0.0.1:8088/superset/dashboard/1/)**

_Note: You may also create your own metrics, charts & dashboards._

_Note: Very large datasets may eventually cause timeouts loading charts. If this happens, refresh a few at a time._
```

I guess just removing that would make them relative? Worth checking in the code if this affects anything other than the welcome markdown files.

### PR DESCRIPTION
**Pull request by smacker**
Fix #211: Relative URLs in welcome dashboard markdown
Fix #174: Welcome Dashboard Title styling on markdown files
Fix #162: Charts disalignment in Collaboration dashboard

Signed-off-by: Maxim Sukharev <max@smacker.ru>

### CODE REVIEW

**Comment by carlosms** [comment]
Question: does `[list of dashboards](/dashboard/list/)` still work if superset is deployed in a sub path?

e.g. for the URL `http://example.com/my-sourced/`, the welcome will be `http://example.com/my-sourced/superset/welcome`.
The link to `/dashboard/list/` will link to `http://example.com/dashboard/list/`, without `/my-sourced`, and fail.

Is my assumption correct?

**Comment by smacker** [comment]
@carlosms Superset doesn't support deployment on sub path. XHR requests will fail. See for example this file: https://github.com/src-d/sourced-ui/blob/master/superset/superset/assets/src/SqlLab/actions/sqlLab.js#L130

**Comment by smacker** [comment]
or maybe I'm wrong: https://github.com/apache-superset/superset-ui/blob/master/packages/superset-ui-connection/src/SupersetClientClass.ts#L169

we need to test if it works.

**Comment by smacker** [comment]
I tested. Static doesn't load.
Screenshot 2019-07-18 at 12 21 38

I checked the config and templates and looks like base url can't be changed. But even if it's possible we don't expose this setting outside.

**Pull request merged**
