### PR TITLE
Fix development mode in docker for macOs

### PR DESCRIPTION
**Pull request by smacker**
I wasn't able to run sourced-ui container in dev mode on my machine.
It took more than 10m to reach `npm ci` step with consistent close to
100% CPU load.

This commit fixes it by:
- Mounting source code with `consistency: delegated` which is the faster
mode to bind mount
- Use docker volume for `node_modules` to avoid syncing it with host
file system at all

Required changes:
- Use root user in dev mode always, not only for Linux
- Set superset user to `node_modules` volume, by default only root has
access to it
- Replace `npm ci` with `npm install` because `npm ci` removes
`node_modules` directory before starting installing dependencies. But
mounted directory can't be removed.

Signed-off-by: Maxim Sukharev <max@smacker.ru>

---

* [x] I have updated the CHANGELOG file according to the conventions in [keepachangelog.com](https://keepachangelog.com)
* [ ] This PR contains changes that do not require a mention in the CHANGELOG file

### CODE REVIEW

**Comment by smacker** [comment]
@se7entyse7en could you please validate it works for you? AFAIK you also use macOs.

**Comment by se7entyse7en** [comment]
> @se7entyse7en could you please validate it works for you? AFAIK you also use macOs.

yup, I'm on OSX. Gonna test it 👍.

**Comment by se7entyse7en** [comment]
I tried to test this. I built a docker image starting from this branch, and set `SUPERSET_ENV: development` in the compose file. Then I ran `make dev-prepare` separately and then restarted using sourced-ce. I tried changing the `font-size` for the `body, html` rule in `override.less`, but nothing happens and the page is not reloaded. By from the console I have this:

Screenshot 2019-08-29 at 12 06 48

What am I missing?

**Comment by smacker** [comment]
1. This commit doesn't change how hot reloading works
2. You shouldn't change anything in compose file
3. I'm not sure which `override.less` you are talking about. The one in bblfsh? Then you need to open UAST tab.
4. I just re-tested with a change in `srcd/superset/assets/stylesheets/less/custom-brand.less` and
Screenshot 2019-08-29 at 12 38 16
5. I rebased on master & re-pushed so it will use new superset

**Comment by se7entyse7en** [comment]
Retested it and worked flawlessly! Thanks! 👏

**Comment by smacker** [comment]
Great. Merging because we have no other macOs guys in the team.

**Comment by dpordomingo** [comment]
@ricardobaeta this fix should also work for you, and speed up your development in Mac.
Could you confirm that hot reloading is now working for you?

btw. Many thanks @smacker for your fix!!

**Pull request merged**
