### PR TITLE
Fix chart height in dashboard

### LINKED ISSUE #200: "Files missing summary" table needs to be taller
From 0.4.0-beta.1

image

### PR DESCRIPTION
**Pull request by carlosms**
Fix #200

### CODE REVIEW

**Comment by carlosms** [comment]
Yes, this is the json as is it was exported by the `superset export_dashboards` command.

**Comment by smacker** [comment]
there are some unnecessary objects exported because removing them isn't implemented yet

**Comment by carlosms** [comment]
> there are some unnecessary objects exported because removing them isn't implemented yet

So can we mrege this PR as it is, or I should redo this json manually?

**Comment by smacker** [comment]
It will be imported correctly. But for the sake of clearness, I would change this one field manually.
Fix for export is on the way. Will be ready today/tomorrow.

**Comment by carlosms** [comment]
Done and force-pushed.

**Pull request merged**
