### PR TITLE
Improve charts display on local and orgs dashboards

### PR DESCRIPTION
**Pull request by gomesfernanda**
This PR covers/solves:

- [Issue 153](https://github.com/src-d/sourced-ui/issues/153): Repository count on preset dashboard is rounded
- [Issue 155](https://github.com/src-d/sourced-ui/issues/155): Preset chart: "Number of commits per month breakdown per repo" legend taking too much space
- [Issue 115](https://github.com/src-d/sourced-ui/issues/115): Incorrect chart for releases
- Changes "X Axis Format" to *mmm/yy* on charts
- Releases chart:
	a) Granularity: monthly
	b) Stack repository columns
	c) Fix query to major versions `v%.%.0` and `%.%.0`
	d) Exclude 2015 filter on query
	e) Exclude legend
- Change some charts title to be shorter and more meaningful
- Divide screen 50/50 between the charts "Average time to merge" and "Breakdown by pull request outcome"

This PR does NOT cover [Issue 140](https://github.com/src-d/sourced-ui/issues/140) (Most active repos chart isn't sorted by value) and the reason is explained on the issue itself.

**Screenshots of Overview dashboard:**
welcome1_20190623
welcome2_20190623
welcome3_20190623
welcome4_20190623
welcome5_20190623

**Screenshots of Collaboration dashboard:**

collaboration1_20190623
collaboration2_20190623
collaboration3_20190623

Signed-off-by: Fernanda Gomes <fergomes@gmail.com>

### CODE REVIEW

**Comment by marnovo** [comment]
BTW do we need to do something related to this for this PR to be properly merged?

[(from Slack)](https://src-d.slack.com/archives/GKDAJP6F9/p1561138730027500)

> Important note about dashboards!
> 
> There are lots of ids everywhere and if we mess with them everything breaks.
> It’s very very difficult to fix ids manually, I tried but there are just too many of them.
> I also see when we use cli for the export, it re-generates ids for existing dashboard in master. Most probably because there are “gaps” in ids.
> So any new dashboards based on current master will be broken. (I’ll have to redo metadata dashboard completely now :cry: )
> Cli exports all the dashboards together but we need them separately (so for local repos mode there is no metadata dashboard).
> 
> What it means to us:
> 1. We can’t work on dashboards in parallel.
> 2. After export we need to makes sure there is no “gaps”
> 3. We have to split results of export into different json files manually (no only “dashboard” object but `__SqlaTable__` as well)
> 4. DON’T MERGE ANY CHANGES TO DASHBOARDS WITHOUT TESTING IT ON EMPTY DB

**Comment by se7entyse7en** [comment]
I'm testing this locally, and it seems that some query are broken. Most probably due to what @marnovo  mentioned about the export/import of dasboards that @smacker explained.

**Comment by smacker** [comment]
For me charts aren't broken by incorrect datasource but at least releases charts doesn't contain any fixes.

I also checked the json. Export was done wrong.
I don't know how to fix it except redo on clean instance and export properly.

**Comment by se7entyse7en** [comment]
Also having this, but I don't know what could be the reason.

Screenshot 2019-06-24 at 12 20 37

**Comment by se7entyse7en** [comment]
I had the doubt that I wasn't using latest `master`. After retrying I still have [this](https://github.com/src-d/sourced-ui/pull/158#issuecomment-504933665), but not [this](https://github.com/src-d/sourced-ui/pull/158#issuecomment-504951267).

**Comment by smacker** [comment]
it is done wrong. I'll re-create a new PR with the same (most probably partially) changes.

**Pull request closed without merging**
