### PR TITLE
Update superset to v0.34.0rc1

### PR DESCRIPTION
**Pull request by smacker**
Fix: #250 

Update log is here: https://gist.github.com/smacker/b703b2ac21a76b10c76d8944030022b5 (might be useful for review)

This PR requires manual testing. I have tested it myself but could miss something.

---

* [x] I have updated the CHANGELOG file according to the conventions in [keepachangelog.com](https://keepachangelog.com)
* [ ] This PR contains changes that do not require a mention in the CHANGELOG file

### CODE REVIEW

**Comment by se7entyse7en** [comment]
I haven't tested this yet, but I think we most probably need to have `db_engine_specs/sparksql.py`, don't we?

**Comment by smacker** [comment]
@se7entyse7en I put spark definition inside `hive` file as it mostly just inherits `hive` engine. If we continue to override methods we can always move it to a separate file.

**Comment by se7entyse7en** [comment]
I tried locally and there's only one thing that didn't work for me. In SQL Lab tab if I try to get the preview of the `commits` table, here's what I get:

Screenshot 2019-08-27 at 17 31 10


And this is the stacktrace:
```
sourced-ui_1    | 2019-08-27 15:29:33,574:ERROR:root:'array_type'
sourced-ui_1    | Traceback (most recent call last):
sourced-ui_1    |   File "/home/superset/superset/sql_lab.py", line 146, in get_sql_results
sourced-ui_1    |     start_time=start_time,
sourced-ui_1    |   File "/home/superset/superset/sql_lab.py", line 323, in execute_sql_statements
sourced-ui_1    |     selected_columns, data
sourced-ui_1    |   File "/home/superset/superset/db_engine_specs/presto.py", line 757, in expand_data
sourced-ui_1    |     column["name"], column["type"].lower(), all_columns
sourced-ui_1    |   File "/home/superset/superset/db_engine_specs/presto.py", line 172, in _parse_structural_column
sourced-ui_1    |     column_name, presto_type_map[field_info[1]]()
sourced-ui_1    | KeyError: 'array_type'
```

**Comment by se7entyse7en** [comment]
I tried getting the preview of all tables and this seems the only one having problems.

**Comment by smacker** [comment]
@se7entyse7en does it work on master? Do you think it makes sense to track this issue separately as it related to sparksql only?

**Comment by se7entyse7en** [comment]
@smacker I tested on latest released version (`v0.5.0`) and it works fine.

> Do you think it makes sense to track this issue separately as it related to sparksql only?

It's totally fine for me. 👍

**Pull request merged**
