### PR TITLE
Branding typography

### LINKED ISSUE #114: Tables overflow the chart container
Screenshot 2019-06-17 at 12 22 20

I thought it would be possible to fix with making the container bigger but it fixes the issue only when the table is small. For a table with many elements changing size of the chart doesn't help.

### LINKED ISSUE #122: Buttons looks incorrent
After redesign:
Screenshot 2019-06-17 at 12 45 41

Before:
Screenshot 2019-06-17 at 12 46 59

### LINKED ISSUE #123: Table headers look incorrect
After redesign.

Before:
Screenshot 2019-06-17 at 12 47 51

After:
Screenshot 2019-06-17 at 12 47 42

### LINKED ISSUE #124: Close button isn't clickable on sqllab params
After redesign the "x" in popup doesn't react on anothing:

Screenshot 2019-06-17 at 12 51 20

### LINKED ISSUE #125: Top menu looks incorrect
After redesign.

Before:
Screenshot 2019-06-17 at 12 54 02

After:
Screenshot 2019-06-17 at 12 53 57

### LINKED ISSUE #134: Manual testing for typography branch
1. Checkout to [`sourced-ui-branding`](https://github.com/src-d/sourced-ui/tree/sourced-ui-branding) branch
2. Rebase it on master if needed
3. Go through [issues related to branding/typography](https://github.com/src-d/sourced-ui/labels/typography), make sure they are fixed
4. Go through pages see that nothing new is broken
5. Create a PR from the branch (or commit if the branch contains non-typography commits already)

### PR DESCRIPTION
**Pull request by dpordomingo**
fix #134
fix #125
fix #124
fix #123
fix #122
fix #114

The new typography was introduced by https://github.com/src-d/sourced-ui/pull/106, but some days later it was reverted by https://github.com/src-d/sourced-ui/pull/128, so its changes were rollbacked.

Original changes made by https://github.com/src-d/sourced-ui/pull/106 were: 555765c25772120e699ef00164e622739a524304 450de62cee59cb1e01f453e98ded99c40e2a6559 43ba635032dabf0970c378425ec64572357a2807 a20fde3579c84f0aaf4c16943203facc85ea33ae ec5d9ed75e77bc37e786cb2a95763e19bf07ca0f 0414d65ee72f4dd9156f063459d5805938d02a74

After being reverted, an extra commit was applied on top of those ones: abb3431bd47b98bf6a6551f3a2a3069de9964672 to address the problems described by #125 #124 #123 #122

As requested by #134, I took the old work and applied on top of the current `master` in order to validate and merge it.

<details>
<summary><i>click to see more details of how the previous commits were rearranged on top of `master`</i></summary>
1. I took all the old six commits from above and rebase-squashed them into: d8b774bd <br />
2. And then applied <del>abb3431bd47b98bf6a6551f3a2a3069de9964672</del> &rarr; c828320a on top, to fix the described problems. <br />
3. Create this PR with the new two commits, containing the old and outdated commits.
</details>

Some screenshots testing it over the current `sourced v0.14.0-beta.5 `

Old view:
image

New view:
image

New `collaboration` dashboard:
image

### CODE REVIEW

**Comment by dpordomingo** [comment]
Let me know if I should do any other testing, please.

**Comment by smacker** [comment]
plz this one as well https://github.com/src-d/sourced-ui/issues/113
also try to click on dropdowns and other stuff on charts creation page to makes sure nothing is broken there

**Comment by smacker** [comment]
according to screenshot, #114 and #118 aren't fixed, right?

**Comment by ricardobaeta** [comment]
> according to screenshot, #114 and #118 aren't fixed, right?

No @smacker , we talked about this and we agreed that chart fixing with be easily taken care by you. Can you confirm, please?

**Comment by smacker** [comment]
@ricardobaeta 
as it is described in #114 apparently it isn't easily fixable on our side, my initial guess was wrong.

#113 is important. As I described in the comment it prevents modifying/creating a chart with a long title. And it's not always possible (for example on my laptop) to make the browser window bigger to workaround the problem. In pre-redesign, similar issue exists but much less bad. The chart also gets moved down but x-axis is still visible.

**Comment by ricardobaeta** [comment]
@smacker please have in mind [@dpordomingo comment](https://github.com/src-d/sourced-ui/issues/113#issuecomment-504024504) on #113.

**Comment by smacker** [comment]
David said exactly the same what I did in the comment above but in more words:
- bug exists in master too
- solution is `Long title s...`

**Comment by dpordomingo** [comment]
I think we should not block the typography redesign by issues that are already happening in current `master` or are not caused by that redesign itself.
Considering that:
- #113 (On chart edit page a chart isn't visible fully) &rarr; not caused by the redesign, more details, and possible workaround at https://github.com/src-d/sourced-ui/issues/113#issuecomment-504024504
- #114 (Tables overflow the chart container) &rarr; already addressed by 2e1a31e
- #118 (Summary chart overflow) &rarr; not a css issue but a dashboard layout problem (solved by #129).

My proposal for this PR:
- test it deeply with latest `sourced-ce` and our two available dashboards.
  - Confirm that already known regressions are solved:
    - #114 (Tables overflow the chart container)
    - #125 (Top menu looks incorrect)
    - #124 (Close button is not clickable)
    - #123 (Incorrect table headers)
    - #122 (Buttons looks like wrong)
  - Perform an extra sanity check
    - dropdowns, chart creation section, uast... and such
  - Merge
  - Do not block for non regressions:
    - #113 (On chart edit page a chart isn't visible fully)
    - #118 (Summary chart overflow)

**Comment by marnovo** [comment]
@dpordomingo agreed.

**Comment by smacker** [comment]
Let's rebase on master and check with new charts. For the rest looks like everybody agrees it's good to go already and we can merge.

**Comment by dpordomingo** [comment]
1. I rebased over current master,
2. built a new image and tried it with new `sourced`,
3. confirmed that all blockers described by `(2)` at https://github.com/src-d/sourced-ui/pull/139#issuecomment-504033936 are still solved,
4. quick sanity check `(3)` confirming that there are not huge outages in:
  - our current 3 dashboards,
  - chart creation,
  - dashboard creation and reordering charts
  - running queries in SQL Lab
  - viewing UASTs

imo this is ready again to be considered as good to go.

**Comment by dpordomingo** [comment]
Since https://github.com/src-d/sourced-ui/pull/142 was made on top of this one, you might prefer to deeply test the other one, and approve this one if #142 pass your tests :D

**Comment by dpordomingo** [comment]
I leave here, per @smacker requirement, some screenshots showing how blocker issues were solved, and how the new UI looks like if this and https://github.com/src-d/sourced-ui/pull/142 are merged.

#125 (Top menu looks incorrect)
#122 (Buttons looks like wrong) 
image

#124 (popups with not clickable close button)
image

#123 (Incorrect table headers) 
image

Collaborative dashboard
collaborative

Overview dashboard
#114 (Tables overflow the chart container) 
overview

Welcome dashboard
welcome

Chart creation
image

Bblfsh tab
image

SQL Lab
image

**Comment by ricardobaeta** [comment]
@dpordomingo @smacker @carlosms I've just noticed that the Title on the Welcome Dashboard is not using Source Sans Pro. 

On the welcome dashboard markdown files we have:

```
.dashboard-markdown .dashboard-component.dashboard-component-chart-holder h1 {
    margin-top: 24px;
    margin-bottom: 24px;
    line-height: 1.6;
    font-size: 30px;
    font-weight: bold;
```

And we just need to add:

```
font-family: Source Sans Pro, Helvetica Neue, Arial, sans-serif;
```

Before:
image

After:
image

**Comment by carlosms** [comment]
I see the UAST tab changes some of the global styles. I have only noticed it in the top-right "New" button, it gets bigger. But there might be other places:

a

b

**Comment by carlosms** [comment]
Why don't we fix #118 in this PR too @dpordomingo? I mean editing the chart height in the dashboard json.

**Comment by carlosms** [comment]
I've noticed the sql lab results table now has an extra outer scrollbar. See before:
b-scroll

And after:
a-scroll

**Comment by carlosms** [comment]
I've found a missing change in button height. In this case it's a minor thing, but it means there might be other places where buttons are not consistent.

Before:
Peek 2019-06-28 10-39

After:
Peek 2019-06-28 10-38

**Comment by marnovo** [comment]
Looking great. :)

Regarding the inconsistencies at @carlosms has shown… @dpordomingo @ricardobaeta would this be something that we would fix/avoid by figuring out [the puzzle with the "global variables"](https://github.com/src-d/sourced-ui/issues/132) (i.e. being able to properly set/propagate styles top-down) first?

**Comment by smacker** [comment]
jfyi

> extra outer scrollbar

I experienced this before (not sure if with current sourced-ui or the one based on previous superset 0.32)

**Comment by carlosms** [comment]
Also as can be seen in the previous comment https://github.com/src-d/sourced-ui/pull/139#issuecomment-506671899, the UAST button inside the results table now overlaps one row with the next one, and does not look as neat.

**Comment by dpordomingo** [comment]
Do we want to release the branding once we can guarantee that it has 0 errors? or do we assume that there can be small issues to be solved in an iterative process?

I understood that it was accepted that some parts could be addressed separately as long as it would not impact heavily in the UX. I assume that we considered it because it was agreed that the benefits of having a rebranded site, are higher than the costs of having some dangling elements, pending to be adapted.

Do the arisen issues cause more damage, than the benefit of the rebranding as this PR and https://github.com/src-d/sourced-ui/pull/142 propose?

For sure I'm not saying that we should not fix any small problem we find, nor they're not important, nor we should not deeply review the design. What I think is that we should consider if those issues impact more to the user than the benefit of merging and then continue improving in shorter iterations.

Once said that, let's consider each reported issue:
- [ ] #183(UAST tab changes some global styles)
- [ ] #186 (UAST buttons in result tables has no margins)
- [ ] #118 (Summary chart overflow)
    - we could change dashboards charts in this PR, but I think it would be better if done in a separate PR #187. Why? I think it's better to separate theming PR from dashboards (e.g. since this PR increase the fonts, we could also consider increasing other charts, and not only this one, like proposed by https://github.com/src-d/sourced-ui/issues/162)
- [ ] #184 (Extra outer scrollbar in SQL lab results)
    - that problem already exists in `srcd/sourced-ui:v0.3.0-rc.1` as described in the issue.
- [ ] #185 (Buttons does not keep the size on action)
    - the problem appears now in two axes, but it was previously happening in one because x-axis should not change on action.

Should we block this PR until we deeply review this redesign to ensure there is no other issue like the ones reported above? Are we going to exhaustively review all the PRs addressing the rebranding? Or are we only doing sanity checks before merging, and considering the rebranding as something that will be done iteratively?

**Pull request merged**
