### PR TITLE
Add taking the integer part as a number format option

### PR DESCRIPTION
**Pull request by warenlg**
Signed-off-by: Waren Long <waren@sourced.tech>

Fix https://github.com/src-d/sourced-ui/issues/248

### CODE REVIEW

**Comment by carlosms** [comment]
@warenlg would it be possible to submit this change upstream, as a PR to https://github.com/apache/incubator-superset?

**Comment by warenlg** [comment]
Yes of course

**Comment by smacker** [comment]
Maybe [SMART_NUMBER formatter](https://github.com/apache-superset/superset-ui/pull/109) which is [default](https://github.com/apache/incubator-superset/pull/7137) now in upstream is a better solution for this problem.

**Comment by warenlg** [comment]
Yes indeed, SMART_NUMBER is doing the job, thanks

**Pull request closed without merging**
