### PR TITLE
This adds branding to the UAST Lab

### PR DESCRIPTION
**Pull request by ricardobaeta**
image

Signed-off-by: Ricardo Baeta <ricardo@ricardobaeta.com>

### CODE REVIEW

**Comment by carlosms** [comment]
The only problem I've found is the style for disabled buttons.

In here you can see the SEARCH button correctly changes the color when it is enabled/disabled. Well, the change is maybe too subtle, but it is there:
a

But for LOAD/SHARE there is not change in style when they are enabled/disabled. When I paste the url https://gist.githubusercontent.com/carlosms/77fe0df0b1b371b9b165abe984ea2560/raw/ab6037be92fb90f42b9468de17d3bcf2b7268d81/hello.java in the text field the only way to know they are active is the shadow on hover. The color does not change, like with SEARCH.
b

**Comment by ricardobaeta** [comment]
Thanks @carlosms for the catch! The latest commit `7cee8b0` fixes this bug.

**Comment by carlosms** [comment]
Exactly, maybe I didn't explain myself in my previous comment, but the gif shows how LOAD and SHARE don't change the style for enabled/disabled, while SEARCH has this subtle change in color.

Since 7cee8b0 removes the shadow on hover for active buttons, now there is absolutely no visual cue to know if LOAD or SHARE are enabled/disabled.

**Comment by ricardobaeta** [comment]
@carlosms and @dpordomingo :) Thanks for pointing out the traits of this behaviour. I wasn't fully understanding the interaction before, and now I do, and know how we can improve it.

Details of my latest commit `60fac18`:

1) The text on the input of the Raw Gist URL has now proper typography styling.
2) The buttons - LOAD & SHARE & SEARCH - have now a :hover effect when they're active.
3) A button should always react to people's interaction - hover/click - despite being inactive. Having this in mind, I add a subtle behaviour to these inactive buttons.

load-share-search

**Comment by dpordomingo** [comment]
For me, the new change is enough to merge. We can iterate in another PR, considering the following issues:
- #206 Inconsistencies in inactive buttons 
- #207 Inconsistencies in auto-filled inputs

**Pull request merged**
