### PR TITLE
Add initial support for org sync mode

### PR DESCRIPTION
**Pull request by smacker**
- Add SYNC_MODE env var to enable it
- Automatically create metadata datasource (uses main DB server)
- Split dashboards into 2 directories gitbase and metadata
- Add placeholder for welcome dashboard
- Make welcome dashboard a default

Fix: #107

### CODE REVIEW

**Comment by carlosms** [comment]
looks good, although I did not try it locally.
Needs to be included in the README.

**Comment by smacker** [comment]
rebased on master, included in README

**Comment by smacker** [comment]
I will wait with merge until we have v0.3.0 just in case.

**Comment by smacker** [comment]
PR updated to follow flake8 codestyle. It was tested together with ghcollecter and ghsync on srcd-ce. => merging.

**Pull request merged**
