### PR TITLE
Dashboard tweaks

### PR DESCRIPTION
**Pull request by carlosms**
See #158.

- Remove the float formatting on Y Axis of "Most active repositories" chart
- Change X Axis of “# of pull requests created” and “average time to merge” to mmm/yy (%b/%y)
- Divide screen 50/50 between the charts “Average time to merge” and “Breakdown by pull request outcome"

### CODE REVIEW

**Comment by se7entyse7en** [comment]
I've tested this locally. It works, but the only thing that I noticed is this disalignment at the bottom:

Screenshot 2019-06-24 at 17 11 47

**Comment by smacker** [comment]
confirm dis-alignment (I didn't notice it)

**Comment by se7entyse7en** [comment]
but it seems that it was also present in @gomesfernanda's original PR, so in case it's going to slow us too much we could just close this as-is and improve it post-release.

**Comment by se7entyse7en** [comment]
Created this issue #162.

**Pull request merged**
