### PR TITLE
Import dashboard set user

### PR DESCRIPTION
**Pull request by smacker**
Fix: #188

Based on #197 (skip the first commit).

### CODE REVIEW

**Comment by smacker** [comment]
I'll appreciate some help with the manual testing here as well. This PR finishes "import" part. It would still produce strange json on export but that json should be imported correctly now.

**Comment by carlosms** [comment]
I was testing export/import from the UI.

This is the json file exported for a new dashboard created entirely from scratch.
https://gist.github.com/carlosms/3a64244caa5a364809e249590d858bba

And this is the error I get on the UI when I try to upload it:
```
Sorry, something went wrong
500 - Internal Server Error
Stacktrace
         Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/superset/superset/models/core.py", line 1197, in wrapper
    value = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/home/superset/superset/views/core.py", line 1266, in import_dashboards
    dashboard_import_export.import_dashboards(db.session, f.stream)
  File "/home/superset/superset/utils/dashboard_import_export.py", line 27, in import_dashboards
    data = json.loads(data_stream.read(), object_hook=decode_dashboards)
  File "/usr/local/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/superset/superset/utils/core.py", line 251, in decode_dashboards
    return models.Slice(**o['__Slice__'])
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 441, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 438, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 836, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 262, in __set__
    instance_state(instance), instance_dict(instance), value, None
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 1293, in set
    new_values, old_collection, new_collection, initiator=evt
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/collections.py", line 790, in bulk_replace
    constants = existing_idset.intersection(values or ())
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 615, in intersection
    result._members.update(self._working_set(members).intersection(other))
TypeError: unhashable type: 'dict'
```

**Comment by smacker** [comment]
thanks! could you please add steps to reproduce how to generate such dashboard?

**Comment by carlosms** [comment]
It looks like this:
image

This is the output of 'show record' from the dashboard list (copied from the UI table):
```
Title	New dashboard
Slug	None
Owners	[admin admin]
Position JSON	{"CHART-LWGFsBU5Uq":{"children":[],"id":"CHART-LWGFsBU5Uq","meta":{"chartId":33,"height":50,"sliceName":"New chart","width":4},"parents":["ROOT_ID","GRID_ID","ROW-FI1Mkm3tNQ","COLUMN-fIT6UaV0ft"],"type":"CHART"},"COLUMN-fIT6UaV0ft":{"children":["MARKDOWN-xqvMdelAcT","CHART-LWGFsBU5Uq"],"id":"COLUMN-fIT6UaV0ft","meta":{"background":"BACKGROUND_TRANSPARENT","width":7},"parents":["ROOT_ID","GRID_ID","ROW-FI1Mkm3tNQ"],"type":"COLUMN"},"DASHBOARD_VERSION_KEY":"v2","GRID_ID":{"children":["ROW-FI1Mkm3tNQ"],"id":"GRID_ID","parents":["ROOT_ID"],"type":"GRID"},"HEADER_ID":{"id":"HEADER_ID","meta":{"text":" New dashboard"},"type":"HEADER"},"MARKDOWN-xqvMdelAcT":{"children":[],"id":"MARKDOWN-xqvMdelAcT","meta":{"code":"# New dashbaord\n","height":17,"width":4},"parents":["ROOT_ID","GRID_ID","ROW-FI1Mkm3tNQ","COLUMN-fIT6UaV0ft"],"type":"MARKDOWN"},"ROOT_ID":{"children":["GRID_ID"],"id":"ROOT_ID","type":"ROOT"},"ROW-FI1Mkm3tNQ":{"children":["COLUMN-fIT6UaV0ft"],"id":"ROW-FI1Mkm3tNQ","meta":{"background":"BACKGROUND_TRANSPARENT"},"parents":["ROOT_ID","GRID_ID"],"type":"ROW"}}
CSS	
JSON Metadata	{"remote_id": "35a1a0b8-fdb3-4000-a890-84c8d530ec4b", "filter_immune_slices": [], "timed_refresh_immune_slices": [], "filter_immune_slice_fields": {}, "expanded_slices": {}, "refresh_frequency": 0, "default_filters": "{}"}
Underlying Tables	[gitbase].[gitbase.repositories]
Charts	['New chart']
```
The chart looks like this:
image

image

This is the output of show record from the charts list, copied from the UI table:
```
Owners | [admin admin]
-- | --
admin admin
admin admin
2019-07-05 11:00:17.902751
2019-07-05 11:02:53.910971
New chart
10
table
gitbase.repositories
table
{"adhoc_filters": [], "align_pn": false, "all_columns": ["repository_id"], "color_pn": true, "datasource": "10__table", "granularity_sqla": null, "groupby": [], "include_search": false, "include_time": false, "metrics": [], "order_by_cols": [], "order_desc": true, "page_length": 0, "percent_metrics": [], "row_limit": 10000, "slice_id": 33, "table_filter": false, "table_timestamp_format": "%Y-%m-%d %H:%M:%S", "time_grain_sqla": "P1D", "time_range": "Last week", "timeseries_limit_metric": null, "url_params": {}, "viz_type": "table", "remote_id": "b5a3c78b-41da-4a20-9e24-a01b6766084e", "datasource_name": "gitbase.repositories", "schema": "gitbase.repositories", "database_name": "gitbase"}
None
None
[gitbase].[gitbase.repositories](id:10)
[ New dashboard]
[]
```

The output of `docker-compose exec sourced-ui superset export_dashboards --dashboard-id=6 > ~/new-dashboard-cli.json`

is here https://gist.github.com/carlosms/c58a60950a7c876bc4eff268e50a7a97

**Comment by smacker** [comment]
@carlosms thanks. Fixed.

**Comment by carlosms** [comment]
If I import the same dashboard twice, the second time it replaces the first one, instead of creating 2 as I would expect.
Is it a bug, or done on purpose?

**Comment by smacker** [comment]
It's on purpose. That way you can update the dashboard.
Imagine you have staging and prod instance. You work on staging and export it to prod. You don't want to create a new one each time.

We may consider adding a choice to a user override or create a new one later though.

**Comment by carlosms** [comment]
I think it would be less surprising to have the import create a new ID by default, and replace only an existing one if you use some option, like `import_dashboard --id 1`.

But OK if you think this fits better our needs now.

**Comment by smacker** [comment]
I didn't change the behavior. It is how superset works right now. If we want to send this fix in upstream we need to preserve it.

**Pull request merged**
