### PR TITLE
Remove python dev dependencies from the image

### PR DESCRIPTION
**Pull request by smacker**
The production image size has decreased from `933MB` to `811MB`.

Fix: #272

Signed-off-by: Maxim Sukharev <max@smacker.ru>

---

* [x] I have updated the CHANGELOG file according to the conventions in [keepachangelog.com](https://keepachangelog.com)
* [ ] This PR contains changes that do not require a mention in the CHANGELOG file

### CODE REVIEW

**Comment by smacker** [comment]
CI is failing, I'm not sure why. Investigating...

**Comment by se7entyse7en** [comment]
> CI is failing, I'm not sure why. Investigating...

Most probably it's because you need to modify `tox.ini` to include installation of extra deps in each tox env. No need to install them in travis step.

**Comment by smacker** [comment]
Yeah. I figured it too. Thanks.

**Comment by smacker** [comment]
rebased to solve conflicts on changelog

**Pull request merged**
